# Generated by Django 2.2.4 on 2019-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
