# Generated by Django 2.2.5 on 2019-09-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alumno_rutina_id'),
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='profesor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='home.Profesor'),
            preserve_default=False,
        ),
    ]
