# Generated by Django 2.2.4 on 2019-08-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='detalle_id',
            field=models.ManyToManyField(to='rutina.Detalle', verbose_name='Detalle'),
        ),
    ]
