# Generated by Django 2.2.4 on 2019-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_auto_20190904_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['nombre'], 'permissions': (), 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
