# Generated by Django 2.2.5 on 2019-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_rutina_profesor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nivel_exigencia',
            field=models.IntegerField(default=0),
        ),
    ]
