# Generated by Django 2.2.4 on 2019-08-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_auto_20190827_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['nombre'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'ordering': ['nombre'], 'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
    ]
