# Generated by Django 2.2.4 on 2019-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0003_auto_20190827_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='rutina_id',
            field=models.ManyToManyField(to='rutina.Rutina'),
        ),
    ]
