# Generated by Django 2.2.5 on 2019-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0004_detalle_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='detalle_id',
            field=models.ManyToManyField(null=True, to='rutina.Detalle', verbose_name='Detalle'),
        ),
    ]
