# Generated by Django 2.2.5 on 2019-09-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0004_auto_20190908_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='profesor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='home.Profesor'),
            preserve_default=False,
        ),
    ]
