# Generated by Django 2.2.5 on 2019-09-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0007_auto_20190910_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='actividad_id',
            field=models.ManyToManyField(blank=True, to='rutina.Actividad', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='home.Profesor'),
        ),
    ]
