# Generated by Django 2.2.5 on 2019-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0008_auto_20190910_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='detalle_id',
            field=models.ManyToManyField(to='rutina.Detalle', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='actividad_id',
            field=models.ManyToManyField(to='rutina.Actividad', verbose_name='Actividad'),
        ),
    ]
