# Generated by Django 2.2.5 on 2019-09-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0009_auto_20190910_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
