# Generated by Django 2.2.5 on 2019-09-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0010_auto_20190911_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='musculo',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
