# Generated by Django 2.2.5 on 2019-09-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0011_auto_20190911_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='nivel_exigencia',
        ),
    ]
