# Generated by Django 2.2.5 on 2019-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0012_remove_actividad_nivel_exigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='detalle_id',
            field=models.ManyToManyField(null=True, to='rutina.Detalle', verbose_name='Detalle'),
        ),
    ]
