# Generated by Django 2.2.5 on 2019-09-13 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0013_auto_20190912_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='detalle_id',
            field=models.ManyToManyField(to='rutina.Detalle', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle',
            name='categoria',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle',
            name='musculo',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
