# Generated by Django 2.2.5 on 2019-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0014_auto_20190913_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_id', models.ManyToManyField(to='rutina.Actividad', verbose_name='Nivel')),
                ('nivel_id', models.ManyToManyField(to='rutina.Nivel', verbose_name='Nivel')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='nivel_id',
            field=models.ManyToManyField(to='rutina.Nivel', verbose_name='Nivel'),
        ),
    ]
