# Generated by Django 2.2.5 on 2019-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0015_auto_20190914_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeticion',
            name='repeticionesMinimas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repeticion',
            name='actividad_id',
            field=models.ManyToManyField(to='rutina.Actividad', verbose_name='Actividad'),
        ),
    ]
