# Generated by Django 2.2.5 on 2019-09-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0016_auto_20190914_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['nombre'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['nombre'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='repeticion',
            options={'ordering': ['id'], 'verbose_name': 'Repeticion', 'verbose_name_plural': 'Repeticiones'},
        ),
    ]
