# Generated by Django 2.2.5 on 2019-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0019_auto_20190914_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
