# Generated by Django 2.2.5 on 2019-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0020_auto_20190923_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre'),
        ),
    ]
