# Generated by Django 2.2.5 on 2019-10-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20191002_1359'),
        ('rutina', '0023_auto_20191003_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionnivel',
            name='profesor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeEN', to='home.Profesor'),
            preserve_default=False,
        ),
    ]
