# Generated by Django 2.2.5 on 2019-10-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0024_evaluacionnivel_profesor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionnivel',
            options={'ordering': ['nivel_id'], 'verbose_name': 'Evaluacion de nivel', 'verbose_name_plural': 'Evaluaciones de nivel'},
        ),
    ]
