# Generated by Django 2.2.5 on 2019-10-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20191002_1359'),
        ('rutina', '0025_auto_20191003_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.Actividad', verbose_name='Actividad')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeAS', to='home.Alumno')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homePS', to='home.Profesor')),
                ('rutina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.Rutina', verbose_name='Rutina')),
            ],
        ),
    ]
