# Generated by Django 2.2.5 on 2019-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0026_sesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fechaSesion'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesion'},
        ),
        migrations.AddField(
            model_name='sesion',
            name='fechaSesion',
            field=models.DateField(null=True),
        ),
    ]
