# Generated by Django 2.2.5 on 2019-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0027_auto_20191003_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='gif_actividad'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fechaSesion',
            field=models.DateField(null=True, verbose_name='Fecha de la sesion'),
        ),
    ]
