# Generated by Django 2.2.5 on 2019-10-09 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0028_auto_20191004_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionnivel',
            name='profesor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeEN', to='home.Profesor'),
        ),
    ]
