# Generated by Django 2.2.5 on 2019-10-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0029_auto_20191009_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='cantSesiones',
            field=models.IntegerField(default=1, verbose_name='Sesiones parciales'),
            preserve_default=False,
        ),
    ]
