# Generated by Django 2.2.5 on 2019-10-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0030_sesion_cantsesiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='sesionesRealizadas',
            field=models.IntegerField(default=1, verbose_name='Sesiones totales'),
            preserve_default=False,
        ),
    ]
