# Generated by Django 2.2.5 on 2019-10-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0032_auto_20191009_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaSesion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de la sesion'),
        ),
    ]
