# Generated by Django 2.2.5 on 2019-10-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0034_auto_20191011_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='actividad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutina.Actividad', verbose_name='Actividad'),
        ),
    ]
