# Generated by Django 2.2.5 on 2019-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0035_auto_20191011_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='cantSesiones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sesiones parciales'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='esfuerzoSesion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Costo de sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='sesionesRealizadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sesiones totales'),
        ),
    ]
