# Generated by Django 2.2.5 on 2019-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0036_auto_20191011_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='actividad_id',
        ),
        migrations.AddField(
            model_name='sesion',
            name='actividad_id',
            field=models.ManyToManyField(blank=True, null=True, to='rutina.Actividad', verbose_name='Actividad'),
        ),
    ]
