# Generated by Django 2.2.5 on 2019-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0037_auto_20191011_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'get_latest_by': ['fechaSesion'], 'ordering': ['fechaSesion'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesion'},
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fechaSesion',
            field=models.DateField(null=True, verbose_name='Fecha de la sesion'),
        ),
    ]
