# Generated by Django 2.2.5 on 2019-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0038_auto_20191011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaSesion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la sesion'),
        ),
    ]
