# Generated by Django 2.2.5 on 2019-10-14 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20191002_1359'),
        ('rutina', '0039_auto_20191011_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'get_latest_by': 'fechaSesion', 'ordering': ['fechaSesion'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesion'},
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRevision', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeAR', to='home.Alumno')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homePR', to='home.Profesor')),
            ],
        ),
    ]
