# Generated by Django 2.2.5 on 2019-10-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0042_auto_20191013_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='clase_revision',
            field=models.BooleanField(default=False),
        ),
    ]
