# Generated by Django 2.2.5 on 2019-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0043_sesion_clase_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='clase_revision',
        ),
        migrations.AddField(
            model_name='sesion',
            name='claseRevision',
            field=models.BooleanField(default=False, verbose_name='Clase de revision'),
        ),
    ]
