# Generated by Django 2.2.5 on 2019-10-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0044_auto_20191014_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
