# Generated by Django 2.2.5 on 2019-10-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0047_esfuerzoactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esfuerzoactividad',
            name='actividad_id',
        ),
        migrations.AddField(
            model_name='esfuerzoactividad',
            name='actividad_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutina.Actividad', verbose_name='Actividad'),
            preserve_default=False,
        ),
    ]
