# Generated by Django 2.2.5 on 2019-10-25 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_fichaalumno_circunferenciamuneca'),
        ('rutina', '0048_auto_20191025_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfuerzoactividad',
            name='alumno_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeASEA', to='home.Alumno'),
            preserve_default=False,
        ),
    ]
