# Generated by Django 2.2.5 on 2019-10-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0049_esfuerzoactividad_alumno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='esfuerzoSesion',
        ),
    ]
