# Generated by Django 2.2.5 on 2019-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0050_remove_sesion_esfuerzosesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='esfuerzoSesion',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
