# Generated by Django 2.2.5 on 2019-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0051_sesion_esfuerzosesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='esfuerzoSesion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
