# Generated by Django 2.2.5 on 2019-10-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0054_revisionsesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisionsesion',
            options={'get_latest_by': 'fechaRevision', 'ordering': ['fechaRevision'], 'verbose_name': 'Revision de sesion', 'verbose_name_plural': 'Revisiones de sesion'},
        ),
    ]
