# Generated by Django 2.2.5 on 2019-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0055_auto_20191031_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionsesion',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
