# Generated by Django 2.2.5 on 2019-10-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0056_auto_20191031_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionsesion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisionsesion',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
