# Generated by Django 2.2.5 on 2019-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0058_auto_20191031_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsesion',
            name='pesoActual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='revisionsesion',
            name='pesoRevision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
