# Generated by Django 2.2.5 on 2019-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0060_auto_20191101_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionsesion',
            name='nivelAnterior',
            field=models.CharField(max_length=60, verbose_name='Nivel anterior'),
        ),
        migrations.AlterField(
            model_name='revisionsesion',
            name='nivelRevision',
            field=models.CharField(max_length=60, verbose_name='Nivel revision'),
        ),
    ]
