# Generated by Django 2.2.5 on 2019-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0061_esfuerzoactividad_nivel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='nivelSesion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nivel de sesion'),
        ),
    ]
