# Generated by Django 2.2.4 on 2019-08-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=60)),
                ('contrasena', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=70)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=60)),
                ('fechaNac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=25)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
