# Generated by Django 2.2.5 on 2019-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=60)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=25)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
