# Generated by Django 2.2.5 on 2019-09-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
