# Generated by Django 2.2.5 on 2019-09-08 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20190908_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
