# Generated by Django 2.2.5 on 2019-09-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
        ('home', '0002_auto_20190909_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rutina_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Rutina', verbose_name='Rutina'),
        ),
    ]
