# Generated by Django 2.2.5 on 2019-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190908_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
