# Generated by Django 2.2.5 on 2019-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alumno_rutina_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
