# Generated by Django 2.2.5 on 2019-09-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0003_auto_20190908_1102'),
        ('home', '0004_auto_20190908_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rutina_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Rutina', verbose_name='Rutina'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
