# Generated by Django 2.2.5 on 2019-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fichaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='enfermedades',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='grupo_sanguineo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        )
    ]
