# Generated by Django 2.2.5 on 2019-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190909_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
