# Generated by Django 2.2.5 on 2019-09-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fichaalumno_peso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaalumno',
            options={'ordering': ['id'], 'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
    ]
