# Generated by Django 2.2.5 on 2019-09-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190909_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='alumno_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Alumno'),
            preserve_default=False,
        ),
    ]
