# Generated by Django 2.2.5 on 2019-09-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fichaalumno_alumno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rutina_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Rutina', verbose_name='Rutina'),
            preserve_default=False,
        ),
    ]
