# Generated by Django 2.2.5 on 2019-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190910_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaalumno',
            options={'ordering': ['alumno_id'], 'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
    ]
