# Generated by Django 2.2.5 on 2019-09-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190911_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaalumno',
            name='enfermedades',
        ),
        migrations.AlterField(
            model_name='fichaalumno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
