# Generated by Django 2.2.5 on 2019-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190913_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='sexo',
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='profesion',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
