# Generated by Django 2.2.5 on 2019-09-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0019_auto_20190914_1102'),
        ('home', '0014_auto_20190914_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nivel_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Nivel', verbose_name='Nivel'),
            preserve_default=False,
        ),
    ]
