# Generated by Django 2.2.5 on 2019-09-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alumno_nivel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nivel_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Nivel', verbose_name='Nivel'),
        ),
    ]
