# Generated by Django 2.2.5 on 2019-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190923_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='dia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
