# Generated by Django 2.2.5 on 2019-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190923_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadprofesor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
