# Generated by Django 2.2.5 on 2019-09-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190923_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadprofesor',
            options={'verbose_name': 'Disponibilidad Profesor', 'verbose_name_plural': 'Disponibilidad Profesor'},
        ),
    ]
