# Generated by Django 2.2.5 on 2019-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190923_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadprofesor',
            options={'ordering': ['horario'], 'verbose_name': 'Disponibilidad Profesor', 'verbose_name_plural': 'Disponibilidad Profesor'},
        ),
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='horario',
            field=models.DateTimeField(null=True),
        ),
    ]
