# Generated by Django 2.2.5 on 2019-09-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190923_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='semana_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Semana', verbose_name='Semana'),
            preserve_default=False,
        ),
    ]
