# Generated by Django 2.2.5 on 2019-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_disponibilidadprofesor_semana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadprofesor',
            name='horario',
            field=models.TimeField(null=True),
        ),
    ]
