# Generated by Django 2.2.5 on 2019-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_disponibilidadprofesor_profesor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
    ]
