# Generated by Django 2.2.5 on 2019-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190923_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
