# Generated by Django 2.2.5 on 2019-09-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_disponibilidadprofesor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nivel_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Nivel', verbose_name='Nivel'),
            preserve_default=False,
        ),
    ]
