# Generated by Django 2.2.5 on 2019-09-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190926_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nivel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Nivel', verbose_name='Nivel'),
        ),
    ]
