# Generated by Django 2.2.5 on 2019-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190926_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
