# Generated by Django 2.2.5 on 2019-09-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_disponibilidadprofesor_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='alumno_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Alumno', verbose_name='Alumno'),
            preserve_default=False,
        ),
    ]
