# Generated by Django 2.2.5 on 2019-09-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20190927_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadprofesor',
            name='alumno_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Alumno', verbose_name='Alumno'),
        ),
    ]
