# Generated by Django 2.2.5 on 2019-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190928_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
