# Generated by Django 2.2.5 on 2019-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_semana_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='semana_id',
            field=models.ManyToManyField(to='home.Semana', verbose_name='Dias'),
        ),
    ]
