# Generated by Django 2.2.5 on 2019-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alumno_semana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semana_id',
            field=models.ManyToManyField(blank=True, null=True, to='home.Semana', verbose_name='Dias'),
        ),
    ]
