# Generated by Django 2.2.5 on 2019-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20191002_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semana_id',
            field=models.ManyToManyField(blank=True, to='home.Semana', verbose_name='Dias'),
        ),
    ]
