# Generated by Django 2.2.5 on 2019-10-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20191002_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='circunferenciaMuneca',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
