# Generated by Django 2.2.5 on 2019-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_fichaalumno_circunferenciamuneca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaalumno',
            name='circunferenciaMuneca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
