# Generated by Django 2.2.5 on 2019-11-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20191028_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rutina_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to='rutina.Rutina', verbose_name='Rutina'),
        ),
    ]
