# Generated by Django 2.2.5 on 2019-11-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20191105_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default=1, max_length=60, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
