# Generated by Django 2.2.5 on 2019-11-11 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20191110_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaalumno',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fichaalumno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(0)]),
        ),
    ]
