# Generated by Django 2.2.5 on 2019-11-11 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20191111_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaalumno',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='fichaalumno',
            name='circunferenciaMuneca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='fichaalumno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(20)]),
        ),
    ]
