# Generated by Django 2.2.5 on 2019-11-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alumno_fechacambioentrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaCambioEntrenamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cambio de entrenamiento'),
        ),
    ]
