# Generated by Django 2.2.5 on 2019-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['user'], 'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
    ]
