# Generated by Django 2.2.5 on 2019-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20191202_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
